import { useState } from 'react'
import type { Hub, MetricKey } from '../types'
import { METRICS, metricValue } from '../data/hubs'
import { icbByCode } from '../data/icbToGlh'
import { MAP_WIDTH, MAP_HEIGHT, useMap } from '../hooks/useMap'

// ---------------------------------------------------------------------------
// Real ICB-level map of England (ONS ICB April 2026 boundaries, 36 ICBs),
// grouped into the 7 GLHs. Boundary files are generated by
// scripts/build-map.mjs; projection follows the fingertips-dashboard map
// (linear lng/lat → SVG, see src/hooks/useMap.ts).
//
// Interaction is at ICB level: clicking an ICB selects it AND its parent GLH,
// so all GLH-level panels keep working. Shading is by the parent GLH's value
// on the active metric (the data is GLH-level today); if ICB-level data
// arrives later, shade per ICB here and nothing else needs to change.
// ---------------------------------------------------------------------------

const LIGHT = [238, 244, 241]
const DARK = [14, 79, 75]

function scaleColor(t: number): string {
  const c = LIGHT.map((l, i) => Math.round(l + (DARK[i] - l) * t))
  return `rgb(${c[0]}, ${c[1]}, ${c[2]})`
}

interface Props {
  hubs: Hub[]
  metric: MetricKey
  selectedId: string
  selectedIcb: string | null
  onSelectIcb: (icbCode: string, glhId: string) => void
}

export default function RegionMap({ hubs, metric, selectedId, selectedIcb, onSelectIcb }: Props) {
  const { icbPaths, glhPaths } = useMap()
  const [hoveredIcb, setHoveredIcb] = useState<string | null>(null)

  const values = hubs.map((h) => metricValue(h, metric))
  const min = Math.min(...values)
  const max = Math.max(...values)
  const norm = (v: number) => (max === min ? 0.5 : (v - min) / (max - min))
  const hubById = new Map(hubs.map((h) => [h.id, h]))

  const fillFor = (glhId: string) => {
    const hub = hubById.get(glhId)
    if (!hub) return scaleColor(0)
    return scaleColor(0.12 + norm(metricValue(hub, metric)) * 0.88)
  }

  const hovered = hoveredIcb ? icbByCode[hoveredIcb] : null
  const hoveredHub = hovered ? hubById.get(hovered.glhId) : null
  const selected = selectedIcb ? icbByCode[selectedIcb] : null
  const selectedHub = hubs.find((h) => h.id === selectedId)
  const selectedPath = icbPaths.find((p) => p.props.icbCode === selectedIcb)

  return (
    <div className="map__wrap">
      <svg
        className="map__svg"
        viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`}
        preserveAspectRatio="xMidYMid meet"
        role="group"
        aria-label="Map of England's 36 Integrated Care Boards, grouped into the 7 Genomic Laboratory Hubs"
      >
        {/* ICB polygons — the interactive layer */}
        {icbPaths.map(({ props, d }) => {
          const hub = hubById.get(props.glhId)
          const dimmed = hoveredIcb !== null && hoveredIcb !== props.icbCode
          return (
            <path
              key={props.icbCode}
              className={`map__icb${dimmed ? ' map__icb--dim' : ''}`}
              d={d}
              fill={fillFor(props.glhId)}
              tabIndex={0}
              role="button"
              aria-label={`${props.icbName}, ${hub?.name ?? 'unknown'} hub`}
              aria-pressed={props.icbCode === selectedIcb}
              onClick={() => onSelectIcb(props.icbCode, props.glhId)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  onSelectIcb(props.icbCode, props.glhId)
                }
              }}
              onMouseEnter={() => setHoveredIcb(props.icbCode)}
              onMouseLeave={() => setHoveredIcb(null)}
              onFocus={() => setHoveredIcb(props.icbCode)}
              onBlur={() => setHoveredIcb(null)}
            />
          )
        })}

        {/* GLH outlines — visual grouping, not interactive. The selected
            GLH is drawn last: neighbouring outlines share borders, so
            anything drawn later would overpaint the highlight in white,
            leaving only the coastline highlighted. */}
        {glhPaths.filter(({ glhId }) => glhId !== selectedId).map(({ glhId, d }) => (
          <path key={glhId} className="map__glh" d={d} />
        ))}
        {glhPaths.filter(({ glhId }) => glhId === selectedId).map(({ glhId, d }) => (
          <path key={glhId} className="map__glh map__glh--selected" d={d} />
        ))}

        {/* Selected ICB outline, drawn last so it sits above the GLH lines */}
        {selectedPath && <path className="map__icbsel" d={selectedPath.d} />}
      </svg>

      {/* Hover tooltip, pinned bottom-centre like the fingertips map */}
      {hovered && (
        <div className="map__tooltip">
          <strong>{hovered.icbName}</strong>
          <span>
            {hoveredHub
              ? `${hoveredHub.name} GLH · ${METRICS[metric].format(metricValue(hoveredHub, metric))}`
              : 'No hub data'}
          </span>
        </div>
      )}

      {/* Caption under the map: current selection */}
      <div className={`map__caption${selected ? ' map__caption--active' : ''}`}>
        {selected && selectedHub
          ? `${selected.icbName} — ${selectedHub.name} GLH`
          : 'Interactive map — click an ICB'}
      </div>
    </div>
  )
}
