import { useEffect, useRef, useState } from 'react'
import type { Hub, MetricKey } from '../types'
import { METRICS, metricValue } from '../data/metrics'
import { icbByCode } from '../data/icbToGlh'
import { MAP_WIDTH, MAP_HEIGHT, useMap } from '../hooks/useMap'

// ---------------------------------------------------------------------------
// Real ICB-level map of England (ONS ICB April 2026 boundaries, 36 ICBs),
// grouped into the 7 GLHs. Boundary files are generated by
// scripts/build-map.mjs; projection follows the fingertips-dashboard map
// (linear lng/lat → SVG, see src/hooks/useMap.ts).
//
// Interaction is at ICB level: clicking an ICB selects it AND its parent GLH,
// so all GLH-level panels keep working. Shading is by the parent GLH's value
// on the active metric (the data is GLH-level today); if ICB-level data
// arrives later, shade per ICB here and nothing else needs to change.
// ---------------------------------------------------------------------------

const LIGHT = [238, 244, 241]
const DARK = [14, 79, 75]

function scaleColor(t: number): string {
  const c = LIGHT.map((l, i) => Math.round(l + (DARK[i] - l) * t))
  return `rgb(${c[0]}, ${c[1]}, ${c[2]})`
}

// ---------------------------------------------------------------------------
// Zoom / pan — the viewBox is the zoom state. Zooming shrinks the viewBox
// around a focal point (cursor position or view centre); panning translates
// it. MIN_SCALE keeps the whole map in frame; MAX_SCALE caps how far in a
// user can go on the smallest ICB.
// ---------------------------------------------------------------------------

const MIN_SCALE = 1
const MAX_SCALE = 8
const WHEEL_ZOOM_FACTOR = 1.2
const BUTTON_ZOOM_FACTOR = 1.5
const DRAG_THRESHOLD_PX = 3

interface ViewBox {
  x: number
  y: number
  w: number
  h: number
}

const HOME_VIEW: ViewBox = { x: 0, y: 0, w: MAP_WIDTH, h: MAP_HEIGHT }

function clampViewBox(vb: ViewBox): ViewBox {
  const w = Math.min(HOME_VIEW.w, Math.max(HOME_VIEW.w / MAX_SCALE, vb.w))
  const h = w * (HOME_VIEW.h / HOME_VIEW.w)
  const x = Math.min(HOME_VIEW.w - w, Math.max(0, vb.x))
  const y = Math.min(HOME_VIEW.h - h, Math.max(0, vb.y))
  return { x, y, w, h }
}

function zoomViewBox(vb: ViewBox, factor: number, focusX: number, focusY: number): ViewBox {
  const w = vb.w / factor
  const h = vb.h / factor
  const ratioX = (focusX - vb.x) / vb.w
  const ratioY = (focusY - vb.y) / vb.h
  return clampViewBox({ x: focusX - ratioX * w, y: focusY - ratioY * h, w, h })
}

interface Props {
  hubs: Hub[]
  metric: MetricKey
  selectedId: string
  selectedIcb: string | null
  onSelectIcb: (icbCode: string, glhId: string) => void
}

export default function RegionMap({ hubs, metric, selectedId, selectedIcb, onSelectIcb }: Props) {
  const { icbPaths, glhPaths } = useMap()
  const [hoveredIcb, setHoveredIcb] = useState<string | null>(null)

  const svgRef = useRef<SVGSVGElement>(null)
  const [viewBox, setViewBox] = useState<ViewBox>(HOME_VIEW)
  const viewBoxRef = useRef(viewBox)
  useEffect(() => {
    viewBoxRef.current = viewBox
  }, [viewBox])

  const wasDraggedRef = useRef(false)
  const [isDragging, setIsDragging] = useState(false)

  // Wheel zoom needs preventDefault to stop page scroll, but React's
  // synthetic onWheel is passive by default — attach a native listener
  // instead so the browser actually honours it.
  useEffect(() => {
    const svg = svgRef.current
    if (!svg) return
    const handleWheel = (e: WheelEvent) => {
      e.preventDefault()
      const rect = svg.getBoundingClientRect()
      const vb = viewBoxRef.current
      const focusX = vb.x + ((e.clientX - rect.left) / rect.width) * vb.w
      const focusY = vb.y + ((e.clientY - rect.top) / rect.height) * vb.h
      const factor = e.deltaY < 0 ? WHEEL_ZOOM_FACTOR : 1 / WHEEL_ZOOM_FACTOR
      setViewBox((prev) => zoomViewBox(prev, factor, focusX, focusY))
    }
    svg.addEventListener('wheel', handleWheel, { passive: false })
    return () => svg.removeEventListener('wheel', handleWheel)
  }, [])

  const scale = MAP_WIDTH / viewBox.w
  const canZoomIn = scale < MAX_SCALE - 0.01
  const canZoomOut = scale > MIN_SCALE + 0.01

  function zoomByButton(factor: number) {
    const vb = viewBoxRef.current
    setViewBox(zoomViewBox(vb, factor, vb.x + vb.w / 2, vb.y + vb.h / 2))
  }

  function resetZoom() {
    setViewBox(HOME_VIEW)
  }

  // Deliberately not using setPointerCapture here: capturing the pointer on
  // the <svg> retargets the browser's compatibility mousedown/mouseup/click
  // events to the <svg> too, so a plain click on a child ICB <path> would
  // never reach its own onClick. Tracking the drag via window listeners
  // (only while a drag is in progress) leaves normal clicks on the paths
  // completely untouched.
  function handlePointerDown(e: React.PointerEvent<SVGSVGElement>) {
    if (e.button !== 0) return
    wasDraggedRef.current = false
    const svg = e.currentTarget
    const startX = e.clientX
    const startY = e.clientY
    const startView = viewBoxRef.current

    const handleMove = (ev: PointerEvent) => {
      const rect = svg.getBoundingClientRect()
      const dxClient = ev.clientX - startX
      const dyClient = ev.clientY - startY
      if (Math.abs(dxClient) > DRAG_THRESHOLD_PX || Math.abs(dyClient) > DRAG_THRESHOLD_PX) {
        wasDraggedRef.current = true
        setIsDragging(true)
      }
      const dx = (dxClient / rect.width) * startView.w
      const dy = (dyClient / rect.height) * startView.h
      setViewBox(clampViewBox({ ...startView, x: startView.x - dx, y: startView.y - dy }))
    }
    const handleUp = () => {
      setIsDragging(false)
      window.removeEventListener('pointermove', handleMove)
      window.removeEventListener('pointerup', handleUp)
    }
    window.addEventListener('pointermove', handleMove)
    window.addEventListener('pointerup', handleUp)
  }

  const values = hubs.map((h) => metricValue(h, metric))
  const min = Math.min(...values)
  const max = Math.max(...values)
  const norm = (v: number) => (max === min ? 0.5 : (v - min) / (max - min))
  const hubById = new Map(hubs.map((h) => [h.id, h]))

  const fillFor = (glhId: string) => {
    const hub = hubById.get(glhId)
    if (!hub) return scaleColor(0)
    return scaleColor(0.12 + norm(metricValue(hub, metric)) * 0.88)
  }

  const hovered = hoveredIcb ? icbByCode[hoveredIcb] : null
  const hoveredHub = hovered ? hubById.get(hovered.glhId) : null
  const selected = selectedIcb ? icbByCode[selectedIcb] : null
  const selectedHub = hubs.find((h) => h.id === selectedId)
  const selectedPath = icbPaths.find((p) => p.props.icbCode === selectedIcb)

  return (
    <div className="map__wrap">
      <svg
        ref={svgRef}
        className={`map__svg${isDragging ? ' map__svg--dragging' : ''}`}
        viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.w} ${viewBox.h}`}
        preserveAspectRatio="xMidYMid meet"
        role="group"
        aria-label="Map of England's 36 Integrated Care Boards, grouped into the 7 Genomic Laboratory Hubs. Scroll or use the zoom controls to zoom in."
        onPointerDown={handlePointerDown}
      >
        {/* ICB polygons — the interactive layer */}
        {icbPaths.map(({ props, d }) => {
          const hub = hubById.get(props.glhId)
          const dimmed = hoveredIcb !== null && hoveredIcb !== props.icbCode
          return (
            <path
              key={props.icbCode}
              className={`map__icb${dimmed ? ' map__icb--dim' : ''}`}
              d={d}
              fill={fillFor(props.glhId)}
              tabIndex={0}
              role="button"
              aria-label={`${props.icbName}, ${hub?.name ?? 'unknown'} hub`}
              aria-pressed={props.icbCode === selectedIcb}
              onClick={() => {
                if (wasDraggedRef.current) return
                onSelectIcb(props.icbCode, props.glhId)
              }}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  onSelectIcb(props.icbCode, props.glhId)
                }
              }}
              onMouseEnter={() => setHoveredIcb(props.icbCode)}
              onMouseLeave={() => setHoveredIcb(null)}
              onFocus={() => setHoveredIcb(props.icbCode)}
              onBlur={() => setHoveredIcb(null)}
            />
          )
        })}

        {/* GLH outlines — visual grouping, not interactive. The selected
            GLH is drawn last: neighbouring outlines share borders, so
            anything drawn later would overpaint the highlight in white,
            leaving only the coastline highlighted. */}
        {glhPaths.filter(({ glhId }) => glhId !== selectedId).map(({ glhId, d }) => (
          <path key={glhId} className="map__glh" d={d} />
        ))}
        {glhPaths.filter(({ glhId }) => glhId === selectedId).map(({ glhId, d }) => (
          <path key={glhId} className="map__glh map__glh--selected" d={d} />
        ))}

        {/* Selected ICB outline, drawn last so it sits above the GLH lines */}
        {selectedPath && <path className="map__icbsel" d={selectedPath.d} />}
      </svg>

      {/* Zoom controls, pinned top-right of the map */}
      <div className="map__zoom" role="group" aria-label="Map zoom controls">
        <button
          type="button"
          className="map__zoombtn"
          onClick={() => zoomByButton(BUTTON_ZOOM_FACTOR)}
          disabled={!canZoomIn}
          aria-label="Zoom in"
          title="Zoom in"
        >
          +
        </button>
        <button
          type="button"
          className="map__zoombtn"
          onClick={() => zoomByButton(1 / BUTTON_ZOOM_FACTOR)}
          disabled={!canZoomOut}
          aria-label="Zoom out"
          title="Zoom out"
        >
          −
        </button>
        {canZoomOut && (
          <button
            type="button"
            className="map__zoombtn map__zoombtn--reset"
            onClick={resetZoom}
            aria-label="Reset zoom"
            title="Reset zoom"
          >
            ⟲
          </button>
        )}
      </div>

      {/* Hover tooltip, pinned bottom-centre like the fingertips map */}
      {hovered && (
        <div className="map__tooltip">
          <strong>{hovered.icbName}</strong>
          <span>
            {hoveredHub
              ? `${hoveredHub.name} GLH · ${METRICS[metric].format(metricValue(hoveredHub, metric))}`
              : 'No hub data'}
          </span>
        </div>
      )}

      {/* Caption under the map: current selection */}
      <div className={`map__caption${selected ? ' map__caption--active' : ''}`}>
        {selected && selectedHub
          ? `${selected.icbName} — ${selectedHub.name} GLH`
          : 'Interactive map — click an ICB'}
      </div>
    </div>
  )
}
